---
- hosts: all
  name: instdall python
  gather_facts: false

  tasks:
    - raw: which python || (apt-get update && apt-get install -y python-minimal)

- hosts: all
  name: install lorem
  roles:
    - lorem
